"""" To generate c++ math library code. """


from string import Template


#
# Level 2
#
# 1. Generate C Math Function Directors.
# 2. Generate Types and their Conversion Bodies.
#
#


def generate_main_body() -> str:
    """ Generate the main body of content.
    """
    return ''


#
# Level 1
#
# 1. Call generate_main_body.
# 2. Put the return value inside the main template.
# 3. Write the final result into the output file.
#
#


def write_content(file_path: str, content: str) -> None:
    """Write content to a text file.
    """
    with open(file_path, 'w', encoding='utf-8', newline='\n') as file:
        file.write(content)
        file.close()


MAIN_TEMPLATE: Template = Template("""
// This file is generated by a python script.

#pragma once

namespace ab
{
namespace math
{

$main_content

} // namespace math
} // namespace ab
""".strip() + '\n')

if __name__ == '__main__':
    write_content(
        "ab/code_gen_output_2.hpp",
        MAIN_TEMPLATE.substitute({'main_content': generate_main_body()})
    )
