"""" To generate c++ math library code. """

from code_generation.body import generate_body


def write_content(file_path: str, content: str) -> None:
    """Write content to a text file.
    file_path: Give a full path. (relative or absolute does not matter.)
    content: String of text.
    """
    with open(file_path, 'w', encoding='utf-8', newline='\n') as file:
        file.write(content)
        file.close()


def main() -> None:
    """ Main Template
    """
    result = f"""// This file is generated by a python script.\n
#pragma once\n
namespace ab
{{
namespace math
{{\n
{generate_body()}\n
}} // namespace math
}} // namespace ab
"""
    write_content('ab/code_gen_output.hpp', result)
